<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CarTrack.Modules.Users</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\CarTrack.Api\CarTrack.Api.csproj" />
    <ProjectReference Include="..\..\Shared\CarTrack.Identity\CarTrack.Identity.csproj" />
    <ProjectReference Include="..\..\Shared\CarTrack.Infrastructure\CarTrack.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared\CarTrack.Core\CarTrack.Core.csproj" />
  </ItemGroup>
</Project>
