// <auto-generated />
using System;
using CarTrack.Modules.Tenders;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarTrack.Modules.Tenders.Persistence.Migrations
{
    [DbContext(typeof(TendersDbContext))]
    [Migration("20260716152111_AddTenderSourceCircuitBreaker")]
    partial class AddTenderSourceCircuitBreaker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateOnly?>("ClosingDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<string[]>("DocumentUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("MatchedKeywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PortalStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ClosingDate");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("Status");

                    b.HasIndex("SourceId", "ExternalKey")
                        .IsUnique();

                    b.ToTable("TenderMatches", (string)null);
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("MatchMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<Guid[]>("SourceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.ToTable("TenderQueries", (string)null);
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderScrapeRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("ItemsSkippedExpired")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSkippedKnown")
                        .HasColumnType("integer");

                    b.Property<int>("MatchesNew")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.PrimitiveCollection<Guid[]>("SourceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("SourcesAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("SourcesUnchanged")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("TenderScrapeRuns", (string)null);
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderScrapeRunSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BytesFetched")
                        .HasColumnType("bigint");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsMatched")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSeen")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSkippedExpired")
                        .HasColumnType("integer");

                    b.Property<int>("ItemsSkippedKnown")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("SourceId");

                    b.ToTable("TenderScrapeRunSources", (string)null);
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CircuitOpenedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("ETag")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedHeader")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxDetailPagesPerRun")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("NextDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParserKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("RobotsRespect")
                        .HasColumnType("boolean");

                    b.Property<int?>("ScrapeIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CircuitOpenedUntil");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("NextDueAt");

                    b.ToTable("TenderSources", (string)null);
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderWatchSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyInApp")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("QueryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TenderWatchSubscriptions", (string)null);
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderScrapeRunSource", b =>
                {
                    b.HasOne("CarTrack.Modules.Tenders.TenderScrapeRun", "Run")
                        .WithMany("SourceLogs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("CarTrack.Modules.Tenders.TenderScrapeRun", b =>
                {
                    b.Navigation("SourceLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
